version: '3.8'

services:
  notes-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - notes-net
    restart: unless-stopped

networks:
  notes-net:
    driver: bridge
